import pandas as pd
df=pd.read_csv("/tmp/fdb_repo/compression/cryptos.bz2",compression="bz2",dtype=str,keep_default_na=False)
print("CRYPTOS rows:",len(df),"cols:",list(df.columns))
print()
print("--- 'exchange' value counts (provenance signal) ---")
print(df["exchange"].value_counts().to_string())
print()
print("--- 'currency' (quote) value counts ---")
print(df["currency"].value_counts().to_string())
print()
uq=df["cryptocurrency"].nunique()
print(f"unique 'cryptocurrency' (token ticker) values: {uq}   rows: {len(df)}")
print(f"=> rows are TOKEN x QUOTE-CURRENCY PAIRS, not distinct tokens: ratio {len(df)/uq:.2f}")
print()
print("--- symbol format analysis ---")
print("symbols containing '-':", int(df['symbol'].str.contains('-').sum()))
print("symbols NOT containing '-':", int((~df['symbol'].str.contains('-')).sum()))
print("examples without '-':", df.loc[~df['symbol'].str.contains('-'),'symbol'].head(10).tolist())
print("examples with '-':", df.loc[df['symbol'].str.contains('-'),'symbol'].head(6).tolist())
print()
print("--- same token ticker, multiple rows (symbol collision on TOKEN) ---")
vc=df["cryptocurrency"].value_counts(); print(vc.head(8).to_string())
print()
print("--- CHAIN / ADDRESS evidence: any such column? ---")
for c in ["chain","network","contract","address","contract_address","platform","token_id","decimals","launch_date","first_seen","market_cap","price","volume","liquidity"]:
    print(f"   column '{c}' present: {c in df.columns}")
print()
print("--- chain info only inside free-text summary? ---")
s=df["summary"].str.lower()
for kw in ["ethereum","solana","binance smart chain","bnb","polygon","avalanche","arbitrum","base","tron","cardano"]:
    print(f"   summary mentions '{kw}': {int(s.str.contains(kw,regex=False).sum())}")
print()
print("--- SOL-specific investigation (AHOS core chain) ---")
print("rows whose symbol starts with 'SOL-':", int(df['symbol'].str.startswith('SOL-').sum()))
print("rows whose cryptocurrency == 'SOL':", int((df['cryptocurrency']=='SOL').sum()))
print(df[df['cryptocurrency']=='SOL'][['symbol','name','cryptocurrency','currency','exchange']].to_string(index=False))
print()
print("--- do any Solana-ecosystem tokens appear? (probe a known list) ---")
probe=["BONK","WIF","JUP","PYRM","JTO","RAY","ORCA","MNGO","POPCAT","MEW","BOME","SLERF","MYRO","WEN","TRUMP","FARTCOIN","PNUT","GOAT","ACT","GRIFFAIN","CHILLGUY","MICHI","RETARDIO","NEIRO","MOODENG","GIGA","SPORE","MOCA","AI16Z","VIRTUAL","ZEREBRO","AIXBT","GRASS","HYPE","SUI","APT","SEI","TIA","INJ","ONDO","PEPE","SHIB","DOGE","XRP","BTC","ETH","ADA","AVAX","LINK","UNI","AAVE","MKR","LDO","ARB","OP","MATIC","DOT","ATOM","NEAR","ALGO","FIL","ICP","QNT","VET","HBAR","XLM","ETC","BCH","LTC","TRX","XMR","ZEC","DASH"]
present=[p for p in probe if p in set(df["cryptocurrency"])]
absent=[p for p in probe if p not in set(df["cryptocurrency"])]
print(f"   PRESENT ({len(present)}): {present}")
print(f"   ABSENT  ({len(absent)}): {absent}")
print()
print("--- full sample rows ---")
print(df.head(4).to_string(index=False)[:1500])
print()
print("--- website field: how many distinct / empty ---")
print("empty website:", int((df['website'].str.strip()=='').sum()), " distinct:", df['website'].nunique())
