export type Locale = "fa" | "en";
export const locales: Locale[] = ["fa", "en"];
export const defaultLocale: Locale = "fa";
export function isLocale(x: string): x is Locale {
  return x === "fa" || x === "en";
}
export function getDict(locale: string): Dict {
  return locale === "en" ? en : fa;
}

const fa = {
  dir: "rtl",
  meta: {
    title: "اهوس — اقیانوسِ هوش | سامانهٔ هوش فرصت‌های رمزنگاری",
    description:
      "اهوس: کشف زودهنگام فرصت‌ها، تحقیق عمیق، دروازهٔ امنیتی، شورای خبرگان هوش مصنوعی، آزمایش کاغذی و یادگیری مستمر — با حاکمیت کنترل‌شده.",
  },
  brand: { name: "اهوس", latin: "AHOS", tag: "اقیانوسِ هوش" },
  nav: {
    dashboard: "داشبورد",
    opportunities: "فرصت‌ها",
    council: "شورای خبرگان",
    wiseTree: "درخت خرد",
    paper: "آزمایش کاغذی",
    switchTo: "EN",
  },
  hero: {
    kicker: "سامانهٔ هوش فرصت — سیاست نسخهٔ ۱٫۴٫۲",
    titleA: "از یک چشمهٔ کوچک",
    titleB: "تا اقیانوسی از هوش",
    sub: "اهوس فقط یک ربات معامله‌گر نیست؛ یک موجودِ تحقیقاتی است که فرصت‌ها را زود کشف می‌کند، عمیق بررسی می‌کند، به چالش می‌کشد، تصمیم می‌گیرد، آزمایش می‌کند و از برد و باخت و «عبور» درس می‌گیرد.",
    ctaPrimary: "مشاهدهٔ رتبه‌بندی فرصت‌ها",
    ctaSecondary: "ورود به شورای خبرگان",
    live: "زنده",
    stats: {
      tracked: "توکن تحت پایش",
      decisions: "تصمیم کانونیکال",
      paperPnl: "سود/زیان کاغذی",
      winRate: "نرخ برد",
    },
    funnelBadge: "قیف هوش ۲۴ ساعت گذشته",
  },
  philo: {
    quote:
      "«هدف، پیش‌بینیِ درستِ همه‌چیز نیست؛ هدف این است که هر روز شواهد‌محورتر، امن‌تر و صادق‌تر شویم.»",
    author: "منشور اهوس — بند صفر",
  },
  ticker: { label: "نوار بازار — دادهٔ خواندنی از تصمیم کانونیکال" },
  golden: {
    kicker: "میوهٔ طلایی امروز",
    gatesPassed: "دروازه‌های گذرانده‌شده",
    confidence: "اطمینان کانونیکال",
    viewDossier: "مطالعهٔ پروندهٔ کامل",
    since: "آخرین محاسبه",
    whyTitle: "چرا این فرصت؟",
  },
  funnel: {
    kicker: "قیفِ کیفیت",
    title: "از ۱٬۲۴۰ نامزد، فقط یک میوهٔ طلایی",
    sub: "اهوس تعداد فرصت‌ها را بیشینه نمی‌کند؛ کیفیت را بیشینه می‌کند. «بدون معامله» هم یک پاسخ هوشمندانه است.",
    stages: ["نامزدها", "غربال‌شده", "تحقیق‌شده", "نامزد قوی", "باکیفیت", "استثنایی"],
    note: "نتایج چرخهٔ ۲۴ ساعت گذشته — محاسبه‌شده از تصمیم‌های کانونیکال",
    skip: "عبور (SKIP) همیشه روی میز است.",
  },
  scores: {
    opportunity: "فرصت",
    security: "امنیت",
    liquidity: "نقدینگی",
    whale: "نهنگ‌ها",
    social: "شتاب اجتماعی",
    narrative: "روایت",
    evidence: "شواهد",
    confidence: "اطمینان",
  },
  decision: {
    STRONG_CANDIDATE: "نامزد استثنایی",
    CANDIDATE: "نامزد",
    MONITOR: "تحت پایش",
    SKIP: "عبور هوشمندانه",
    REJECT: "رد قطعی",
  },
  identity: {
    VERIFIED: "هویت تأییدشده",
    CONFLICT: "تعارض هویت",
    UNRESOLVED: "هویت حل‌نشده",
    INVALID: "هویت نامعتبر",
    STALE: "هویت کهنه",
    UNSUPPORTED: "شبکهٔ پشتیبانی‌نشده",
  },
  gate: { PASS: "عبور", REJECT: "رد امنیتی", INCOMPLETE: "ناکامل", STALE: "کهنه" },
  stance: {
    BULLISH: "موافق",
    BEARISH: "مخالف",
    NEUTRAL: "خنثی",
    ABSTAIN: "امتناع",
    ALARM: "هشدار جدی",
  },
  alerts: {
    kicker: "جریان هشدارها",
    title: "رویدادهای تصمیم کانونیکال",
    sub: "هیچ هشداری در فرانت‌اند ساخته نمی‌شود؛ هر رویداد از لایهٔ تصمیم کانونیکال وارد می‌شود.",
    sourceNote: "منبع: لایهٔ تصمیم کانونیکال",
    types: {
      OPPORTUNITY: "فرصت",
      SECURITY: "امنیت",
      IDENTITY: "هویت",
      WHALE: "نهنگ",
      PAPER: "کاغذی",
      DAILY: "گزارش روزانه",
      NEWS: "خبر",
    },
  },
  council: {
    kicker: "شورای خبرگان هوش",
    title: "ده تیم متخصص، یک تصمیم کانونیکال",
    sub: "هوش مصنوعی می‌تواند توصیه کند، به چالش بکشد یا امتناع کند — اما هرگز نمی‌تواند دروازهٔ شکست‌خوردهٔ امنیت را به توصیهٔ مثبت تبدیل کند.",
    session: "جدیدترین جلسهٔ شورا",
    disagreement: "شاخص اختلاف‌نظر",
    onToken: "دربارهٔ",
    calls: "رأی",
    correct: "درست",
    abstain: "امتناع",
    calibration: "کالیبراسیون",
    performance: "کارکرد آزمایشی",
    redTeamNote: "تیم ۰۴ به‌طراحی خصمانه است؛ وظیفه‌اش اثباتِ این است که چرا نباید به توکن اعتماد کرد.",
    viewToken: "پروندهٔ توکن",
    debateFor: "موضوع مناظره",
    finalWord: "رأی نهایی همیشه از لایهٔ تصمیم قطعی صادر می‌شود؛ شورا مشاور است، نه فرمانده.",
  },
  tree: {
    kicker: "درخت خرد",
    title: "هوش، یک موجودِ زنده است",
    sub: "ریشه‌ها منابع داده‌اند، برگ‌ها حس‌گرها، میوه‌ها فرصت‌ها و سنگ‌ها خطاها و APIهای مسدودشده. درخت با هر شواهدِ تأییدشده رشد می‌کند.",
    legend: {
      roots: "ریشه‌ها — منابع داده",
      water: "آب — دانش تأییدشده",
      rocks: "سنگ‌ها — خطا و انسداد",
      branches: "شاخه‌ها — تیم‌های متخصص",
      leaves: "برگ‌ها — حس‌گرها و شواهد",
      fruit: "میوه — فرصت",
      goldenFruit: "میوهٔ طلایی — فرصت استثنایی",
    },
    growth: "وقایع رشد",
    loop: { knowledge: "دانش", decision: "تصمیم", result: "نتیجه", learning: "یادگیری" },
    loopTitle: "چرخهٔ تأثیر",
    notDecider: "درخت خرد تجسمِ منشأ است، نه تصمیم‌گیرنده.",
  },
  providers: {
    kicker: "سلامت منابع",
    title: "پایش ارائه‌دهندگان داده",
    sub: "هیچ ارائه‌دهنده‌ای مالک معماری نیست؛ هر مسدودی به‌صورت شفاف ثبت می‌شود.",
    latency: "تأخیر",
    reliability: "پایداری",
    lastOk: "آخرین موفقیت",
    status: { OK: "سالم", DEGRADED: "کاهش‌یافته", STALE: "کهنه", BLOCKED: "مسدود", FAILING: "ناسالم" },
  },
  learning: {
    kicker: "حلقهٔ یادگیری",
    title: "الگوهای ثبت‌شده از برد، باخت و عبور",
    sub: "هر آزمایش — حتی شکست‌خورده یا ردشده — به دانش تبدیل می‌شود. هیچ الگویی بی‌سند نیست.",
    positive: "الگوی مثبت",
    failure: "الگوی شکست",
  },
  paper: {
    kicker: "آزمایشگاه کاغذی",
    title: "آزمایش بدون پول واقعی، درسِ واقعی",
    sub: "هر موضع کاغذی دارای ورود، حد ضرر، اهداف، کارمزد و بیشینهٔ مدت نگهداری است و تا پایان چرخهٔ عمرش پایش می‌شود.",
    equity: "منحنی خالص تجمعی",
    open: "موضع‌های باز",
    closed: "موضع‌های بسته‌شده",
    postmortem: "کالبدشکافی",
    lesson: "درس ثبت‌شده",
    stats: {
      winRate: "نرخ برد",
      avgWin: "میانگین برد",
      avgLoss: "میانگین باخت",
      maxDrawdown: "بیشینهٔ افت",
      expectancy: "امید ریاضی",
      totalPnl: "نتیجهٔ خالص",
    },
    pos: {
      entry: "ورود",
      current: "جاری",
      exit: "خروج",
      stop: "حد ضرر",
      target: "هدف",
      size: "اندازه",
      opened: "گشوده‌شده",
      closed: "بسته‌شده",
      pnl: "سود/زیان",
      progress: "پیشروی تا هدف",
    },
    result: { WIN: "برد", LOSS: "باخت", TIMEOUT: "پایان‌زمان" },
  },
  opp: {
    kicker: "رتبه‌بندی فرصت‌ها",
    title: "چه کسی شایستگیِ توجه را دارد؟",
    sub: "رتبه بر اساس امتیاز فرصت است؛ اما دروازهٔ هویت و امنیت بالاتر از هر امتیازی قرار دارد.",
    filters: { all: "همه", STRONG_CANDIDATE: "استثنایی", CANDIDATE: "نامزد", MONITOR: "پایش", SKIP: "عبور", REJECT: "ردشده" },
    subScoreLegend: "هشت بُعد مستقل هوش",
    tokenOnly: "فقط پایش توکن — هیچ ادعای نقدینگیِ استخری وجود ندارد",
    noDecision: "بدون تصمیم",
    empty: "هیچ موردی با این پالایه یافت نشد.",
  },
  dossier: {
    kicker: "پروندهٔ اطلاعاتی توکن",
    contract: "قرارداد",
    chain: "زنجیره",
    launch: "راه‌اندازی",
    mcap: "ارزش بازار",
    liq: "نقدینگی",
    vol: "حجم ۲۴س",
    sections: {
      scores: "هشت بُعد هوش",
      gates: "زنجیرهٔ دروازه‌های کانونیکال",
      why: "چرا؟",
      risks: "ریسک‌ها",
      reject: "شرایط رد",
      scenarios: "سناریوها",
      evidenceLedger: "دفتر شواهد",
      councilDebate: "مناظرهٔ شورا",
      paper: "مواجههٔ کاغذی",
    },
    gates: { identity: "هویت", evidence: "شواهد", security: "امنیت", liquidity: "نقدینگی" },
    scenarioKeys: { bull: "صعودی", base: "پایه", bear: "نزولی", extreme: "ریسک حدی" },
    evStatus: { VERIFIED: "تأییدشده", UNVERIFIED: "تأییدنشده", CONFLICTED: "متناقض", STALE: "کهنه" },
    evKind: { MARKET: "بازار", SECURITY: "امنیت", ONCHAIN: "درون‌زنجیره‌ای", SOCIAL: "اجتماعی", IDENTITY: "هویت", NEWS: "خبر" },
    proofNote: "هر گزارهٔ این پرونده به شواهدِ ثبت‌شده قابل‌ردیابی است. دادهٔ نمونه برای محیط توسعه.",
    back: "بازگشت به فرصت‌ها",
    notFound: "پرونده یافت نشد.",
    policy: "سیاست تصمیم",
  },
  atmosphere: {
    engine: "موتور محیط",
    fallback: "موقعیت پیش‌فرض: تهران",
    seasons: { spring: "بهار", summer: "تابستان", autumn: "پاییز", winter: "زمستان" },
    cond: { clear: "صاف", clouds: "ابری", rain: "بارانی", storm: "طوفانی", snow: "برفی", fog: "مه‌آلود" },
    day: "روز",
    night: "شب",
  },
  common: {
    demo: "محیط نمایشی",
    unknown: "ناشناخته",
    insufficient: "شواهد ناکافی",
    source: "منبع",
    confidenceWord: "اطمینان",
  },
  footer: {
    line: "اهوس — سیستم هوش فرصت؛ نه وعدهٔ سود، بلکه انضباطِ شواهد.",
    phase: "فاز ۱ — هوش کشف توکن",
    rights: "پول واقعی در کار نیست. انسان، مسئول تصمیم نهایی است.",
    quote: "هر مانع، داده است. هر عبور، می‌تواند هوشمندانه باشد.",
  },
};
export type Dict = typeof fa;

const en: Dict = {
  dir: "ltr",
  meta: {
    title: "AHOS — Ocean of Intelligence | Crypto Opportunity Intelligence",
    description:
      "AHOS: early opportunity discovery, deep investigation, security gates, an AI expert council, paper experiments and continuous learning — under controlled governance.",
  },
  brand: { name: "AHOS", latin: "اهوس", tag: "Ocean of Intelligence" },
  nav: {
    dashboard: "Command",
    opportunities: "Opportunities",
    council: "Council",
    wiseTree: "Wise Tree",
    paper: "Paper Lab",
    switchTo: "فارسی",
  },
  hero: {
    kicker: "Opportunity intelligence system — policy v1.4.2",
    titleA: "From a small spring",
    titleB: "to an ocean of intelligence",
    sub: "AHOS is not a trading bot. It is a research organism: it discovers early, investigates deeply, challenges its own thesis, decides, paper-experiments, and learns from wins, losses and SKIPs.",
    ctaPrimary: "View opportunity ranking",
    ctaSecondary: "Enter the Council",
    live: "LIVE",
    stats: {
      tracked: "Tokens monitored",
      decisions: "Canonical decisions",
      paperPnl: "Paper PnL",
      winRate: "Win rate",
    },
    funnelBadge: "Intelligence funnel — last 24h",
  },
  philo: {
    quote:
      "“The goal is not to predict everything correctly. The goal is to become more evidence-driven, safer and more honest every day.”",
    author: "AHOS Charter — clause zero",
  },
  ticker: { label: "Market tape — read model of the canonical decision layer" },
  golden: {
    kicker: "Today's golden fruit",
    gatesPassed: "Gates passed",
    confidence: "Canonical confidence",
    viewDossier: "Open full dossier",
    since: "Last computed",
    whyTitle: "Why this opportunity?",
  },
  funnel: {
    kicker: "Quality funnel",
    title: "From 1,240 candidates to a single golden fruit",
    sub: "AHOS does not maximize the number of trades — it maximizes the quality of decisions. “No trade” is a valid intelligent answer.",
    stages: ["Candidates", "Screened", "Investigated", "Strong", "High quality", "Exceptional"],
    note: "Computed from canonical decisions over the last 24h cycle",
    skip: "SKIP is always on the table.",
  },
  scores: {
    opportunity: "Opportunity",
    security: "Security",
    liquidity: "Liquidity",
    whale: "Whales",
    social: "Social velocity",
    narrative: "Narrative",
    evidence: "Evidence",
    confidence: "Confidence",
  },
  decision: {
    STRONG_CANDIDATE: "Exceptional",
    CANDIDATE: "Candidate",
    MONITOR: "Monitoring",
    SKIP: "Intelligent skip",
    REJECT: "Hard reject",
  },
  identity: {
    VERIFIED: "Identity verified",
    CONFLICT: "Identity conflict",
    UNRESOLVED: "Identity unresolved",
    INVALID: "Identity invalid",
    STALE: "Identity stale",
    UNSUPPORTED: "Unsupported chain",
  },
  gate: { PASS: "Pass", REJECT: "Security reject", INCOMPLETE: "Incomplete", STALE: "Stale" },
  stance: {
    BULLISH: "Bullish",
    BEARISH: "Bearish",
    NEUTRAL: "Neutral",
    ABSTAIN: "Abstain",
    ALARM: "Alarm",
  },
  alerts: {
    kicker: "Alert stream",
    title: "Canonical decision events",
    sub: "No alert is ever computed in the frontend; every event arrives from the canonical decision layer.",
    sourceNote: "Source: canonical decision layer",
    types: {
      OPPORTUNITY: "Opportunity",
      SECURITY: "Security",
      IDENTITY: "Identity",
      WHALE: "Whale",
      PAPER: "Paper",
      DAILY: "Daily report",
      NEWS: "News",
    },
  },
  council: {
    kicker: "AI expert council",
    title: "Ten specialist teams, one canonical decision",
    sub: "AI may advise, challenge or abstain — but it can never upgrade a failed identity or security gate into a positive recommendation.",
    session: "Latest council session",
    disagreement: "Disagreement index",
    onToken: "on",
    calls: "calls",
    correct: "correct",
    abstain: "abstains",
    calibration: "calibration",
    performance: "Paper performance",
    redTeamNote: "Team 04 is adversarial by design; its job is to prove why the token should NOT be trusted.",
    viewToken: "Token dossier",
    debateFor: "Debate subject",
    finalWord: "The final word always comes from the deterministic decision layer; the council advises, it does not command.",
  },
  tree: {
    kicker: "The Wise Tree",
    title: "Intelligence is a living organism",
    sub: "Roots are data sources, leaves are sensors, fruits are opportunities, and rocks are failures and blocked APIs. The tree grows with every verified piece of evidence.",
    legend: {
      roots: "Roots — data sources",
      water: "Water — verified knowledge",
      rocks: "Rocks — errors & blocked APIs",
      branches: "Branches — specialist teams",
      leaves: "Leaves — sensors & evidence",
      fruit: "Fruit — opportunity",
      goldenFruit: "Golden fruit — exceptional opportunity",
    },
    growth: "Growth events",
    loop: { knowledge: "Knowledge", decision: "Decision", result: "Result", learning: "Learning" },
    loopTitle: "Impact loop",
    notDecider: "The Wise Tree is provenance visualization — not a decision maker.",
  },
  providers: {
    kicker: "Source health",
    title: "Data provider monitoring",
    sub: "No provider owns the architecture; every outage is recorded transparently.",
    latency: "Latency",
    reliability: "Reliability",
    lastOk: "Last success",
    status: { OK: "Healthy", DEGRADED: "Degraded", STALE: "Stale", BLOCKED: "Blocked", FAILING: "Failing" },
  },
  learning: {
    kicker: "Learning loop",
    title: "Patterns recorded from wins, losses and skips",
    sub: "Every experiment — even a failed or skipped one — becomes knowledge. No pattern exists without evidence.",
    positive: "Positive pattern",
    failure: "Failure pattern",
  },
  paper: {
    kicker: "Paper laboratory",
    title: "Experiments without real money, with real lessons",
    sub: "Every paper position has entry, stop, targets, fees and a maximum holding window — monitored until lifecycle completion.",
    equity: "Cumulative equity curve",
    open: "Open positions",
    closed: "Closed positions",
    postmortem: "Post-mortem",
    lesson: "Recorded lesson",
    stats: {
      winRate: "Win rate",
      avgWin: "Avg win",
      avgLoss: "Avg loss",
      maxDrawdown: "Max drawdown",
      expectancy: "Expectancy",
      totalPnl: "Net result",
    },
    pos: {
      entry: "Entry",
      current: "Current",
      exit: "Exit",
      stop: "Stop",
      target: "Target",
      size: "Size",
      opened: "Opened",
      closed: "Closed",
      pnl: "PnL",
      progress: "Progress to target",
    },
    result: { WIN: "Win", LOSS: "Loss", TIMEOUT: "Timeout" },
  },
  opp: {
    kicker: "Opportunity ranking",
    title: "Who deserves attention?",
    sub: "Ranked by opportunity score — but identity and security gates sit above any score.",
    filters: { all: "All", STRONG_CANDIDATE: "Exceptional", CANDIDATE: "Candidate", MONITOR: "Monitor", SKIP: "Skip", REJECT: "Rejected" },
    subScoreLegend: "Eight independent intelligence dimensions",
    tokenOnly: "Token monitoring only — no pool-level liquidity claim",
    noDecision: "No decision",
    empty: "Nothing matches this filter.",
  },
  dossier: {
    kicker: "Token intelligence dossier",
    contract: "Contract",
    chain: "Chain",
    launch: "Launched",
    mcap: "Market cap",
    liq: "Liquidity",
    vol: "24h volume",
    sections: {
      scores: "Eight dimensions of intelligence",
      gates: "Canonical gate chain",
      why: "Why?",
      risks: "Risks",
      reject: "Reject conditions",
      scenarios: "Scenarios",
      evidenceLedger: "Evidence ledger",
      councilDebate: "Council debate",
      paper: "Paper exposure",
    },
    gates: { identity: "Identity", evidence: "Evidence", security: "Security", liquidity: "Liquidity" },
    scenarioKeys: { bull: "Bull", base: "Base", bear: "Bear", extreme: "Extreme risk" },
    evStatus: { VERIFIED: "Verified", UNVERIFIED: "Unverified", CONFLICTED: "Conflicted", STALE: "Stale" },
    evKind: { MARKET: "Market", SECURITY: "Security", ONCHAIN: "On-chain", SOCIAL: "Social", IDENTITY: "Identity", NEWS: "News" },
    proofNote: "Every statement in this dossier is traceable to recorded evidence. Sample data for the development environment.",
    back: "Back to opportunities",
    notFound: "Dossier not found.",
    policy: "Decision policy",
  },
  atmosphere: {
    engine: "Environment engine",
    fallback: "Fallback location: Tehran",
    seasons: { spring: "Spring", summer: "Summer", autumn: "Autumn", winter: "Winter" },
    cond: { clear: "Clear", clouds: "Cloudy", rain: "Rain", storm: "Storm", snow: "Snow", fog: "Fog" },
    day: "Day",
    night: "Night",
  },
  common: {
    demo: "Demo environment",
    unknown: "Unknown",
    insufficient: "Insufficient evidence",
    source: "Source",
    confidenceWord: "Confidence",
  },
  footer: {
    line: "AHOS — opportunity intelligence; not a promise of profit, but a discipline of evidence.",
    phase: "Phase 1 — Token discovery intelligence",
    rights: "No real money is involved. The human remains responsible for final decisions.",
    quote: "Every obstacle is data. Every skip can be intelligent.",
  },
};
