# AHOS Strategy Research Laboratory — Hypothesis Registry (v2.0)
# RULE: hypotheses registered BEFORE any result is computed. Parameters are a-priori literature
# defaults with documented reasoning. NO tuning on any data to rescue a failing candidate.
HYPOTHESES = [
 dict(id="H1", family="trend_following", name="Donchian Breakout 55/20",
  hypothesis="Sustained breaks of 55-hour price extremes lead to multi-day continuation in crypto majors.",
  reasoning="Classical trend capture (Turtle lineage); crypto exhibits fat-tailed directional runs; CTA/momentum flow reinforces.",
  market_mechanism="Stop-loss cascades + momentum allocator flow beyond visible range highs.",
  required_data="OHLCV 1h, >=3y, majors (liquidity to exit). Have: BTC/ETH/SOL 3.6y BinanceVision.",
  risk_model="SL=2xATR14, TP=none (opposite 20h channel exit), time stop 20d, risk 2% @ max 2x.",
  expected_failure_mode="Choppy ranges whipsaw (bleed via repeated false breaks). Regime-dependence is the known weakness.",
  status="TESTABLE"),
 dict(id="H2", family="mean_reversion", name="Bollinger z20 ±2 reversion",
  hypothesis="Extreme 20h z-score excursions (|z|>2) revert to the 20h mean within ~3 days on BTC/ETH/SOL.",
  reasoning="Short-horizon overreaction/liquidity sweep reversion is among the most replicated effects in liquid crypto pairs.",
  market_mechanism="Market-maker inventory rebalancing after stop hunts; funding-neutral short window.",
  required_data="OHLCV 1h. Have.",
  risk_model="SL=2xATR14, exit at z>=0 (long), time stop 72h, risk 2% @ max 2x.",
  expected_failure_mode="Trend days: repeated re-entry into continuation (slow bleed); fat-tail bar beyond SL gap.",
  status="TESTABLE"),
 dict(id="H3", family="volatility_expansion", name="ATR squeeze breakout",
  hypothesis="Compressed volatility (ATR14 below 0.8x its 100h mean) followed by a 20h-range break leads to expansion moves.",
  reasoning="Volatility clustering (GARCH family effects); squeezes precede expansion in asset vol literature.",
  market_mechanism="Option/market-maker gamma re-hedging when compression ends.",
  required_data="OHLCV 1h. Have.",
  risk_model="SL=1.5xATR14, TP=3xATR14, time stop 48h, risk 2% @ max 2x.",
  expected_failure_mode="False squeeze resolution (quiet continuation); news-spike slippage beyond model.",
  status="TESTABLE"),
 dict(id="H4", family="regime_detection", name="ADX>25 pullback-to-EMA20",
  hypothesis="Entries only in measured trending regimes (ADX14>25) on EMA20 pullbacks beat unconditional entries.",
  reasoning="Trend strategies fail in chop; regime gating targets exactly the H1 failure mode.",
  market_mechanism="Persistent flow imbalance during regime phases (inventory cycles).",
  required_data="OHLCV 1h. Have.",
  risk_model="Close>EMA50 & ADX14>25 & touch EMA20 → LONG (mirror SHORT); SL=1.5xATR, TP=2.5xATR, time 96h;",
  expected_failure_mode="ADX lag: enters late near regime end; fewer trades may fail minimum sample.",
  status="TESTABLE"),
 dict(id="H5", family="funding_rate", name="Extreme funding contrarian",
  hypothesis="Funding ≤ −0.01% (shorts paying heavily) while price above 200h SMA predicts bounce; mirror for +0.01%.",
  reasoning="Perp funding extreme = crowded positioning; unwind pressure favors contrarian entry (documented in perp literature).",
  market_mechanism="Forced deleveraging of the crowded side; funding-arb flow.",
  required_data="8h funding rates. HAVE (real BinanceVision 2023-01→2026-07). Note: last 9 funding days missing (CDN file absence, documented).",
  risk_model="SL=2xATR14, exit on funding normalization (sign flip) or 96h, risk 2% @ max 2x.",
  expected_failure_mode="Funding stays extreme during trending selloffs (catching knife); sparse signals.",
  status="TESTABLE"),
 dict(id="H6", family="open_interest", name="OI expansion + price confirmation",
  hypothesis="Daily OI change > +5% with aligned 24h price move (>|±2%|) confirms committed directional flow → continuation.",
  reasoning="OI growth with price direction indicates new-money conviction rather than short-covering (futures microstructure).",
  market_mechanism="Leverage build-up unwound asymmetrically against late entrants.",
  required_data="Daily OI. HAVE (real daily metrics, 1317 points/symbol).",
  risk_model="SL=1.5xATR14, TP=2xATR14, time stop 72h, risk 2% @ max 2x.",
  expected_failure_mode="OI lags price (daily granularity blurs entry); weekend OI artifacts.",
  status="TESTABLE"),
 dict(id="H7", family="volume_anomaly", name="Volume shock continuation",
  hypothesis="Bars with volume > 2.5x SMA20 AND true range > 1.5x ATR mark informed flow; follow-through next bar.",
  reasoning="Volume-volatility correlation; stealth accumulation/distribution pre-positioning by large players.",
  market_mechanism="Order-flow imbalance persists briefly after information events.",
  required_data="OHLCV 1h. Have.",
  risk_model="SL=1.2xATR14, TP=1.8xATR14, time stop 24h, risk 2% @ max 2x.",
  expected_failure_mode="Exhaustion spikes (final push) revert immediately; news wicks.",
  status="TESTABLE"),
 dict(id="H8", family="liquidity_behavior", name="Order-book imbalance scalping",
  hypothesis="Persistent bid/ask depth imbalance predicts 1-4h drift.",
  reasoning="Microstructure imbalance is the strongest known short-horizon predictor, but requires L2 data.",
  market_mechanism="Maker placement asymmetry.",
  required_data="L2 order book snapshots — NOT AVAILABLE (no source persisted).",
  risk_model="n/a this round.",
  expected_failure_mode="n/a — not testable without data.",
  status="DATA-BLOCKED (registered, not tested — honesty rule)"),
 dict(id="H9", family="multi_factor", name="Fixed-weight composite score",
  hypothesis="Fixed score S = 0.35·tanh(40·(c/ema50−1)) + 0.20·tanh((rsi14−50)/12) + 0.15·tanh(ln(v/sma20v)−0.05) − 0.15·tanh(z20/2) + 0.15·fundingterm; |S|≥0.5 = entry.",
  reasoning="Diversified weak signals may compose; weights chosen a-priori (trend-dominant for crypto); deliberately simple to limit overfit.",
  market_mechanism="Orthogonal flow sources combined.",
  required_data="OHLCV + funding. Have both (real).",
  risk_model="Bracket SL=1.5xATR14 / TP=2xATR14 + score-flip exit, time 96h, risk 2% @ max 2x.",
  expected_failure_mode="Component correlations collapse in stress; weight arbitrariness; mediocre-everywhere risk.",
  status="TESTABLE"),
]
# ---------------- BATCH 2 (registered 2026-08-10, batch-2 multiplicity discipline) ---------------
# Statistical Researcher note: OOS window consumed once by batch 1 (H1-H9). Second-batch candidates
# face a RAISED bar: min_pf_oos = 1.5 (was 1.3). This is a pre-registered multiplicity guard —
# it protects against "second look" selection bias, exactly as pharma keeps alpha-spending budgets.
_NEW = [
 dict(id="H10", family="open_interest+regime", name="OI expansion in high-vol regime only",
  batch=2, gates_override=dict(min_pf_oos=1.5),
  hypothesis="H6's BTC signal (OI growth >5%/day + aligned price move) is regime-bound: it works when realized vol (20h) sits in its upper 500h tercile; neutral otherwise.",
  reasoning="OI expansion indicates leveraged commitment only when the market is moving enough to make leverage dangerous; in quiet regimes OI growth is hedging/market-making noise (batch-1 evidence: train PF 0.35 quiet-heavy window vs OOS PF 3.13 active window).",
  market_mechanism="High-vol OI builds = directional conviction under stress → continuation; low-vol OI builds = basis/hedge flow → no signal.",
  required_data="OHLCV 1h + daily OI. HAVE (real, both).",
  risk_model="SL=1.5xATR14, TP=2xATR14, time stop 72h, risk 2% @ max 2x. Same bracket as H6 — only the REGIME PRECONDITION differs (regime is market state, not a fitted parameter boundary).",
  expected_failure_mode="Tercile boundaries arbitrary; regime flip mid-trade; BTC-only phenomenon may not transfer (acceptability requires ≥2/3 assets). Multiplicity guard: needs PF>1.5.",
  status="TESTABLE"),
 dict(id="H11", family="multi_factor+conviction", name="Composite score, conviction-extremes only",
  batch=2, gates_override=dict(min_pf_oos=1.5),
  hypothesis="H9's composite (fixed weights) has edge only in its extreme tail: entries restricted to |S|≥0.8 carry enough per-trade edge to survive 2x frictions; mid-band signals are noise.",
  reasoning="Batch-1 diagnosis: H9 failed on cost-stress (PF 1.38→0.93 at 2x costs) = edge-per-trade too thin in mid band. Edge density concentrates at score extremes (nonlinear flow agreement).",
  market_mechanism="When trend+volume+funding simultaneously agree at extremes, cross-venue flow alignment exists; partial agreement = conflicting flow.",
  required_data="OHLCV + funding. HAVE (real).",
  risk_model="Bracket SL=1.5xATR14 / TP=2.5xATR14 (wider TP: conviction tails trend), flip-exit at |S|<0.2, time 72h, risk 2% @ max 2x.",
  expected_failure_mode="Sample shrink (fewer trades may fail the ≥30 OOS-trades gate — acceptable falsification); threshold 0.8 is a-priori (top-conviction band), locked at registration.",
  status="TESTABLE"),
 dict(id="H12", family="regime_state_machine", name="RV 3-state machine gating Donchian breaks",
  batch=2, gates_override=dict(min_pf_oos=1.5),
  hypothesis="A 3-state realized-vol state machine (LOW/MID/HIGH by fixed 500h-terciles) resolves H1/H4's regime problem: 20h Donchian breaks taken ONLY in HIGH state survive OOS; ADX was the wrong instrument (lag).",
  reasoning="Batch-1 H1: train PF 1.41 / OOS 0.61 → pure regime rotation. ADX gating (H4) failed due to lag. Realized-vol clustering is the fastest regime proxy with minimal lookback lag.",
  market_mechanism="Breakouts in HIGH-vol states ride existing flow expansion; LOW-state breaks collapse (no participation).",
  required_data="OHLCV 1h. HAVE.",
  risk_model="SL=2xATR14, exit opposite 20h channel, time stop 10d, risk 2% @ max 2x. Donchian 20h (not 55h) because HIGH state is by definition short-lived.",
  expected_failure_mode="HIGH-state entries buy local tops; state estimate at window edges noisy; multiplicity guard PF>1.5.",
  status="TESTABLE"),
]
HYPOTHESES.extend(_NEW)

# ---------------- BATCH 3 (registered 2026-08-11 — PRE-REGISTERED BEFORE ANY RUN) ---------------
_B3 = [
 dict(id="H13", family="open_interest+regime+instrument-scope", name="OI×high-vol, BTC-scoped, 7-year sample",
  batch=3, gates_override=dict(min_pf_oos=1.5),
  hypothesis="The OI-expansion × high-RV-regime mechanism (H10) is a BTC-specific microstructure effect, not a cross-asset law. On extended BTC history (2019-09→2026-08, ~7y) the mechanism yields ≥30 OOS trades and PF>1.5.",
  reasoning="H10 evidence: BTC OOS PF 2.35/WR 68.8%/DD 8.1%/MC 95.2%/stress 1.78 — failed ONLY on sample size (16<30) and cross-asset transfer. Instrument scope is a DESIGN declaration made a priori (BTC = dominant flow venue where OI is most meaningful), NOT a tuning. Extending history to 7y adds regime cycles and sample without touching parameters.",
  market_mechanism="BTC futures OI expansion during high-vol regimes reflects institutional directional commitment (largest, most transparent OI pool in crypto).",
  required_data="BTC 1h OHLCV + funding + daily OI from 2019-09 (BinanceVision futures listing start). ACQUISITION RUN AFTER THIS CARD IS FILED.",
  risk_model="IDENTICAL to H10: SL=1.5xATR14, TP=2xATR14, time 72h, 2% risk @2x — parameters frozen since H10 (scope, not params, is the hypothesis).",
  expected_failure_mode="(a) OI regime edge may be a 2025-26 artifact that decays in older regimes; (b) OOS overlaps batch-1/2 OOS → multiplicity bar PF>1.5 held; (c) metrics files before 2020 may be absent → exclusion logged, never fabricated.",
  multiplicity_note="Third OOS look: bar raised to PF>1.5 (pre-registered). OOS window = final 30% of 7y (~25 months) for sample size.",
  scope=["BTCUSDT"],  # instrument-scope declared PRE-RUN: verdict judged on scope only
  status="TESTABLE"),
]
HYPOTHESES.extend(_B3)

def get(hid): return next(h for h in HYPOTHESES if h["id"] == hid)
