import { PageHeader } from "@/components/dashboard/Shared";
import { ChatPanel } from "@/components/dashboard/ChatPanel";

export const dynamic = "force-dynamic";

export default function AiChatPage() {
  return (
    <div className="flex h-[calc(100vh-140px)] flex-col">
      <PageHeader
        eyebrow="Council Interface"
        title="AI Chat"
        description="Ask AHOS about opportunities, trades, or reasoning. Answers are generated by the local evidence engine — never invented."
      />
      <ChatPanel />
    </div>
  );
}
